/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaMQTT;

import JavaMQTT.ui.MainUI;
import com.formdev.flatlaf.FlatDarkLaf;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public void run() {
        MainUI ui = new MainUI();
        ui.show();
    }

    public static void main(String[] args) {
        FlatDarkLaf.setup();
        new App().run();
    }
}
